name: apple_sign_in_plugin
description: "A comprehensive Flutter package for integrating Apple Sign-In with features for secure authentication and user data management."
version: 1.0.7
repository: https://github.com/Digvijaysinh2204/apple_sign_in_plugin.git
issue_tracker: https://github.com/Digvijaysinh2204/apple_sign_in_plugin/issues
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: '>=1.2.2 <3.0.0'
  jose:  '>=0.3.4 <2.0.0'
  sign_in_with_apple: '>=6.1.4 <8.0.0'
  get_storage: '>=2.1.1 <4.0.0'
  jwt_decoder: '>=2.0.1 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=4.0.0 <8.0.0'

