name: apple_sign_in_plugin
description: "A new Flutter Packages by digvijaysinh."
version: 0.0.1
homepage:
repository: https://github.com/Digvijaysinh2204/apple_sign_in_plugin.git

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  jose: ^0.3.4
  sign_in_with_apple: ^6.1.1
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter: